Adding cache tests
spals/oembed4j pull request #6
Opened 2016-11-21 23:54 UTC by timkral

@thespags 

Adding cache tests.

2016-11-21 23:55 UTC, timkral commented on client/src/main/java/net/spals/oembed4j/client/cache/OEmbedResponseCache.java
> -public class OEmbedResponseCache {
Removing the cache class entirely. The logic was too complex as a separate class.

2016-11-22 00:29 UTC, timkral commented on model/src/main/java/net/spals/oembed4j/model/OEmbedResponse.java
> +    String DEFAULT_VERSION = "1.0";
Moving this so an implementing class can use it without the builder.

2016-11-22 17:17 UTC, thespags requested changes

2016-11-22 17:17 UTC, thespags commented on model/src/main/java/net/spals/oembed4j/model/OEmbedResponse.java
> +    String DEFAULT_VERSION = "1.0";
I've read its best practice is not to place constants in interfaces.

http://stackoverflow.com/questions/320588/interfaces-with-static-fields-in-java-for-sharing-constants

2016-11-22 17:17 UTC, thespags commented on client/src/main/java/net/spals/oembed4j/client/JerseyOEmbedClient.java
>              // TODO: DO we need some real SSL management?
Don't leave todo's

2016-11-22 18:52 UTC, timkral commented on model/src/main/java/net/spals/oembed4j/model/OEmbedResponse.java
> +        public static final String DEFAULT_VERSION = "1.0";
Constant moved back and made public.

2016-11-22 18:53 UTC, timkral commented on client/src/main/java/net/spals/oembed4j/client/JerseyOEmbedClient.java
>              // TODO: DO we need some real SSL management?
That rule assumes we have a bug tracking system setup, which we do not.

2016-11-22 18:59 UTC, timkral commented on client/src/main/java/net/spals/oembed4j/client/JerseyOEmbedClient.java
>              // TODO: DO we need some real SSL management?
Logged: https://github.com/spals/oembed4j/issues/7

FWIW, it was also on my notepad.

2016-11-22 19:49 UTC, merged